version: "3.9"
services:
  # Database
  db:
    image: mysql:8.0
    container_name: fresurfschool-db
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    command: '--default-authentication-plugin=mysql_native_password'
  
  # Wordpress
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fresurfschool-app
    restart: unless-stopped
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - wordpress:/var/www/html
      - ./wordpress_data:/var/www/html/wp-content
    env_file:
      - .env

  # Webserver
  caddy:
    image: caddy:alpine
    container_name: fresurfschool-webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    env_file:
      - .env

volumes:
  db_data:
  caddy_data:
  caddy_config:
  wordpress:

networks:
  default:
    name: fresurfschool