version: "3.9"
services:
  # Database
  db:
    image: mysql:8.0
    container_name: fresurfschool-db
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: e2b5d3a4p7
    command: '--default-authentication-plugin=mysql_native_password'
  
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1-fpm-alpine
    container_name: fresurfschool-app
    restart: unless-stopped
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      MYSQL_ROOT_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin    
      WORDPRESS_DB_PASSWORD: e2b5d3a4p7
      WORDPRESS_TABLE_PREFIX: wp_

  # Webserver
  caddy:
    image: caddy:alpine
    container_name: fresurfschool-webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    environment:
      DOMAIN: "fresurfschool.es"
      EMAIL: "fresurfschool@gmail.com"

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  default:
    name: fresurfschool