name: CI

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: "fresurfschool"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  bkp_scripts:
    runs-on: self-hosted
    steps:
      - name: Backup
        run: |
          if [ -d "./wordpress/wp-content" ]; then
            pwd
            sudo cp -r ./wordpress/wp-content ~/actions-runner/_work/fresurfschool/bkp/
          else
            echo "Folder does not exist."
          fi

  login_scripts:
    runs-on: self-hosted
    needs: [bkp_scripts]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker registry
        run: |
          echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin

  build_scripts:
    runs-on: self-hosted
    needs: [login_scripts]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker build --tag $DOCKERHUB_USERNAME/$APP_NAME:${GITHUB_SHA} .
          docker push $DOCKERHUB_USERNAME/$APP_NAME:${GITHUB_SHA}
          docker image rm --force $DOCKERHUB_USERNAME/$APP_NAME:${GITHUB_SHA}
          docker image prune --force

  deploy_scripts:
    runs-on: self-hosted
    needs: [build_scripts]
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set environment variables
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Deploy
        env:
          APP_NAME: 'fresurfschool'
        run: |
          cp -f ./deploy/docker-compose.override.yml docker-compose.yml
          docker-compose pull --quiet
          docker-compose --project-name "$APP_NAME" up -d --no-build --force-recreate --remove-orphans wordpress
          docker-compose --project-name "$APP_NAME" images
          docker-compose --project-name "$APP_NAME" ps
          sleep 20
          docker-compose --project-name "$APP_NAME" logs --timestamps --tail="all" --no-color > startup.log
          docker image prune --force
      
  # bkp_adding:
  #   runs-on: self-hosted
  #   needs: [deploy_scripts]
  #   steps:
  #     - name: Backup adding
  #       run: |
  #         pwd
  #         sudo cp -r ~/actions-runner/_work/fresurfschool/bkp/wp-content ./wordpress/